import type { FhirBoolean, FhirCanonical, FhirCode, FhirDateTime, FhirString, FhirUri } from "../primitives.js";
import type { Annotation, CodeableConcept, DomainResource, Identifier, Period, Quantity, Range, Ratio, Reference, Timing } from "../datatypes.js";

export interface ServiceRequest extends DomainResource {
  resourceType: "ServiceRequest";
  identifier?: Identifier[];
  instantiatesCanonical?: FhirCanonical[];
  instantiatesUri?: FhirUri[];
  basedOn?: Reference<"CarePlan" | "ServiceRequest" | "MedicationRequest">[];
  replaces?: Reference<"ServiceRequest">[];
  requisition?: Identifier;
  status: FhirCode;
  intent: FhirCode;
  category?: CodeableConcept[];
  priority?: FhirCode;
  doNotPerform?: FhirBoolean;
  code?: CodeableConcept;
  orderDetail?: CodeableConcept[];
  quantityQuantity?: Quantity;
  quantityRatio?: Ratio;
  quantityRange?: Range;
  subject: Reference<"Patient" | "Group" | "Location" | "Device">;
  encounter?: Reference<"Encounter">;
  occurrenceDateTime?: FhirDateTime;
  occurrencePeriod?: Period;
  occurrenceTiming?: Timing;
  asNeededBoolean?: FhirBoolean;
  asNeededCodeableConcept?: CodeableConcept;
  authoredOn?: FhirDateTime;
  requester?: Reference<"Practitioner" | "PractitionerRole" | "Organization" | "Patient" | "RelatedPerson" | "Device">;
  performerType?: CodeableConcept;
  performer?: Reference<"Practitioner" | "PractitionerRole" | "Organization" | "CareTeam" | "HealthcareService" | "Patient" | "Device" | "RelatedPerson">[];
  locationCode?: CodeableConcept[];
  locationReference?: Reference<"Location">[];
  reasonCode?: CodeableConcept[];
  reasonReference?: Reference<"Condition" | "Observation" | "DiagnosticReport" | "DocumentReference">[];
  insurance?: Reference<"Coverage" | "ClaimResponse">[];
  supportingInfo?: Reference<"Resource">[];
  specimen?: Reference<"Specimen">[];
  bodySite?: CodeableConcept[];
  note?: Annotation[];
  patientInstruction?: FhirString;
  relevantHistory?: Reference<"Provenance">[];
}
