import type { SearchParam } from "@fhir-dsl/types";

// --- FhirSchema: the "Database" type for FHIR, like Kysely's Database ---
// Users never write this directly — it's generated by the CLI.
// Intentionally uses `object` constraints to accept concrete interfaces
// without requiring index signatures (same pattern as Kysely's Database type).

// Accepts any object shape — concrete interfaces generated by the CLI satisfy
// this constraint without needing index signatures. Indexed access (S["resources"][RT])
// works because we gate it behind `RT extends keyof S["resources"]` conditionals.
// Uses `any` intentionally at the schema boundary (same pattern as Kysely's Database type).
export interface FhirSchema {
  resources: any;
  searchParams: any;
  includes: any;
  profiles: any;
}

// --- Extract search params for a given resource type ---

export type SearchParamFor<S extends FhirSchema, RT extends string> = RT extends keyof S["searchParams"]
  ? S["searchParams"][RT]
  : Record<string, SearchParam>;

// --- Extract include params for a given resource type ---

export type IncludeFor<S extends FhirSchema, RT extends string> = RT extends keyof S["includes"]
  ? S["includes"][RT]
  : Record<string, string>;

// --- Extract profiles for a given resource type ---

export type ProfileFor<S extends FhirSchema, RT extends string> = RT extends keyof S["profiles"]
  ? S["profiles"][RT]
  : Record<string, never>;

export type ProfileNames<S extends FhirSchema, RT extends string> = RT extends keyof S["profiles"]
  ? string & keyof S["profiles"][RT]
  : never;

export type ResolveProfile<S extends FhirSchema, RT extends string, P extends string | undefined> = P extends string
  ? RT extends keyof S["profiles"]
    ? P extends keyof S["profiles"][RT]
      ? S["profiles"][RT][P]
      : RT extends keyof S["resources"]
        ? S["resources"][RT]
        : never
    : RT extends keyof S["resources"]
      ? S["resources"][RT]
      : never
  : RT extends keyof S["resources"]
    ? S["resources"][RT]
    : never;

// --- Search prefix/operator types based on param type ---

export type DatePrefix = "eq" | "ne" | "gt" | "ge" | "lt" | "le" | "sa" | "eb" | "ap";
export type NumberPrefix = "eq" | "ne" | "gt" | "ge" | "lt" | "le";
export type QuantityPrefix = "eq" | "ne" | "gt" | "ge" | "lt" | "le" | "sa" | "eb" | "ap";
export type StringModifier = "eq" | "contains" | "exact";
export type TokenModifier = "eq" | "not" | "of-type" | "in" | "not-in" | "text" | "above" | "below";
export type ReferenceModifier = "eq";
export type UriModifier = "eq" | "above" | "below";

export type SearchPrefixFor<P> = P extends { type: "date" }
  ? DatePrefix
  : P extends { type: "number" }
    ? NumberPrefix
    : P extends { type: "quantity" }
      ? QuantityPrefix
      : P extends { type: "string" }
        ? StringModifier
        : P extends { type: "token" }
          ? TokenModifier
          : P extends { type: "reference" }
            ? ReferenceModifier
            : P extends { type: "uri" }
              ? UriModifier
              : "eq";

// --- Extract value type from a search param ---

export type ParamValue<P extends SearchParam> = P["value"];

// --- Sort direction ---

export type SortDirection = "asc" | "desc";
