// Re-exports base FHIR datatypes from @fhir-dsl/types
// Bundle/BundleEntry/BundleLink are omitted here — they come from the generated resources/bundle.ts
export type {
  Address,
  Age,
  Annotation,
  Attachment,
  BackboneElement,
  CodeableConcept,
  Coding,
  ContactDetail,
  ContactPoint,
  Contributor,
  Count,
  DataRequirement,
  Distance,
  DomainResource,
  Dosage,
  Duration,
  Element,
  ElementDefinition,
  Expression,
  Extension,
  HumanName,
  Identifier,
  MarketingStatus,
  Meta,
  Money,
  Narrative,
  ParameterDefinition,
  Period,
  Population,
  ProdCharacteristic,
  ProductShelfLife,
  Quantity,
  Range,
  Ratio,
  Reference,
  RelatedArtifact,
  Resource,
  SampledData,
  Signature,
  SimpleQuantity,
  SubstanceAmount,
  Timing,
  TriggerDefinition,
  UsageContext,
} from "@fhir-dsl/types";

import type { Element } from "@fhir-dsl/types";

export interface MoneyQuantity extends Element {}
